<?php

namespace AppBundle\Repository;

/**
 * ActividadServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadServicioRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOtrosTipos($marcaBandera)
    {
        $selectOtrosTipos = $this->createQueryBuilder('a')
            ->Where('a.lavadero IS NOT NULL')
            ->orWhere('a.cambioAceite IS NOT NULL')
            ->orWhere('a.otroSecundario IS NOT NULL')            
            ->andwhere('a.marcaBandera = :marcaBandera ')    
            ->setParameter(':marcaBandera', $marcaBandera)
            ->orderBy('a.id', 'DESC')
            ->getQuery();
        return $selectOtrosTipos->execute();
    }
}
