<?php

namespace AppBundle\Repository;

/**
 * AfectacionARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfectacionARepository extends \Doctrine\ORM\EntityRepository
{
}
