<?php

namespace AppBundle\Repository;

/**
 * AguaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AguaRepository extends \Doctrine\ORM\EntityRepository
{
}
