<?php

namespace AppBundle\Repository;

/**
 * AlmacenamientoTanqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlmacenamientoTanqueRepository extends \Doctrine\ORM\EntityRepository
{
}
