<?php

namespace AppBundle\Repository;

/**
 * AlmacenamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlmacenamientoRepository extends \Doctrine\ORM\EntityRepository
{
}
