<?php

namespace AppBundle\Repository;

/**
 * AreaMedioUrbanizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaMedioUrbanizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
