<?php

namespace AppBundle\Repository;

/**
 * AreaUrbanizacionMedioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaUrbanizacionMedioRepository extends \Doctrine\ORM\EntityRepository
{
}
