<?php

namespace AppBundle\Repository;

/**
 * AreaNaturalProtegidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaNaturalProtegidaRepository extends \Doctrine\ORM\EntityRepository
{
}
