<?php

namespace AppBundle\Repository;

/**
 * BarreraVegetalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarreraVegetalRepository extends \Doctrine\ORM\EntityRepository
{
}
