<?php

namespace AppBundle\Repository;

/**
 * BarreraArtificialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarreraArtificialRepository extends \Doctrine\ORM\EntityRepository
{
}
