<?php

namespace AppBundle\Repository;

/**
 * BocaExpendioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BocaExpendioRepository extends \Doctrine\ORM\EntityRepository
{
}
