<?php

namespace AppBundle\Repository;

/**
 * CaracterizacionEntornoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracterizacionEntornoRepository extends \Doctrine\ORM\EntityRepository
{
}
