<?php

namespace AppBundle\Repository;

/**
 * CategoriaResiduoPeligrosoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaResiduoPeligrosoRepository extends \Doctrine\ORM\EntityRepository
{
}
