<?php

namespace AppBundle\Repository;

/**
 * Certificado_usoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Certificado_usoRepository extends \Doctrine\ORM\EntityRepository
{
}
