<?php

namespace AppBundle\Repository;

/**
 * DestinoSueloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinoSueloRepository extends \Doctrine\ORM\EntityRepository
{
}
