<?php

namespace AppBundle\Repository;

/**
 * DimensionamientoLoteoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DimensionamientoLoteoRepository extends \Doctrine\ORM\EntityRepository
{
}
