<?php

namespace AppBundle\Repository;

/**
 * DimencionamientoPlantaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DimencionamientoPlantaRepository extends \Doctrine\ORM\EntityRepository
{
}
