<?php

namespace AppBundle\Repository;

/**
 * EfluenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EfluenteRepository extends \Doctrine\ORM\EntityRepository
{
}
