<?php

namespace AppBundle\Repository;

/**
 * ElectricaPropiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectricaPropiaRepository extends \Doctrine\ORM\EntityRepository
{
}
