<?php

namespace AppBundle\Repository;

/**
 * ElectricaPorpiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectricaPorpiaRepository extends \Doctrine\ORM\EntityRepository
{
}
