<?php

namespace AppBundle\Repository;

/**
 * EmisionGaseosaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmisionGaseosaRepository extends \Doctrine\ORM\EntityRepository
{
}
