<?php

namespace AppBundle\Repository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEmpresaConPerito($perito)
    {
        return $selectEmpresa = $this->createQueryBuilder('e')
            ->innerJoin('AppBundle:EmpresaHasPerito','ehp','e.id = ehp.empresa')
            ->where('ehp.perito = :perito')
            ->setParameter(':perito', $perito)
            ->getQuery()
            ->execute();
    }
}
