<?php

namespace AppBundle\Repository;

/**
 * EmpresaHasActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaHasActividadRepository extends \Doctrine\ORM\EntityRepository
{
}
