<?php

namespace AppBundle\Repository;

/**
 * EmpresaHasPeritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaHasPeritoRepository extends \Doctrine\ORM\EntityRepository
{
}
