<?php

namespace AppBundle\Repository;

/**
 * EmpresaHasRepresentanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaHasRepresentanteRepository extends \Doctrine\ORM\EntityRepository
{
}
