<?php

namespace AppBundle\Repository;

/**
 * EntidadHasRepositorioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntidadHasRepositorioRepository extends \Doctrine\ORM\EntityRepository
{
}
