<?php

namespace AppBundle\Repository;

/**
 * EtapaConstructivaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapaConstructivaRepository extends \Doctrine\ORM\EntityRepository
{
}
