<?php

namespace AppBundle\Repository;

/**
 * EtapaOperativaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapaOperativaRepository extends \Doctrine\ORM\EntityRepository
{
}
