<?php

namespace AppBundle\Repository;

/**
 * FactibilidadServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactibilidadServicioRepository extends \Doctrine\ORM\EntityRepository
{
}
