<?php

namespace AppBundle\Repository;

/**
 * FactorAfectacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactorAfectacionRepository extends \Doctrine\ORM\EntityRepository
{
}
