<?php

namespace AppBundle\Repository;

/**
 * FormacionPersonalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormacionPersonalRepository extends \Doctrine\ORM\EntityRepository
{
}
