<?php

namespace AppBundle\Repository;

/**
 * ImpactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpactoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findImpactoCantidad($planta, $tipoImpacto)
    {
        $selectCategoryGoldenRules = $this->createQueryBuilder('i')
            ->where('i.tipoImpacto = :tipoimpacto')
            ->andWhere('i.planta = :planta')
            ->setParameter(':tipoimpacto', $tipoImpacto)
            ->setParameter(':planta', $planta)
            ->getQuery();
        return count($selectCategoryGoldenRules->execute());
    }
}
