<?php

namespace AppBundle\Repository;

/**
 * InmuebleAnexoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InmuebleAnexoRepository extends \Doctrine\ORM\EntityRepository
{
}
