<?php

namespace AppBundle\Repository;

/**
 * ListadoTipoResiduoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListadoTipoResiduoRepository extends \Doctrine\ORM\EntityRepository
{
}
