<?php

namespace AppBundle\Repository;

/**
 * ListaTramitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListaTramitesRepository extends \Doctrine\ORM\EntityRepository
{
}
