<?php

namespace AppBundle\Repository;

/**
 * LoteoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoteoRepository extends \Doctrine\ORM\EntityRepository
{
}
