<?php

namespace AppBundle\Repository;

/**
 * MarcaBanderaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcaBanderaRepository extends \Doctrine\ORM\EntityRepository
{
}
