<?php

namespace AppBundle\Repository;

/**
 * MateriaPrimaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateriaPrimaRepository extends \Doctrine\ORM\EntityRepository
{
}
