<?php

namespace AppBundle\Repository;

/**
 * MedidaPreventivaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedidaPreventivaRepository extends \Doctrine\ORM\EntityRepository
{
}
