<?php

namespace AppBundle\Repository;

/**
 * MedidaCorrienteDesechoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedidaCorrienteDesechoRepository extends \Doctrine\ORM\EntityRepository
{
}
