<?php

namespace AppBundle\Repository;

/**
 * MedidaEficienciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedidaEficienciaRepository extends \Doctrine\ORM\EntityRepository
{
}
