<?php

namespace AppBundle\Repository;

/**
 * MemoriaDescriptivaFeedlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemoriaDescriptivaFeedlotRepository extends \Doctrine\ORM\EntityRepository
{
}
