<?php

namespace AppBundle\Repository;

/**
 * MonitoreoResiduoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonitoreoResiduoRepository extends \Doctrine\ORM\EntityRepository
{
}
