<?php

namespace AppBundle\Repository;

/**
 * ObjetoSubdivisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetoSubdivisionRepository extends \Doctrine\ORM\EntityRepository
{
}
