<?php

namespace AppBundle\Repository;

/**
 * OtraEnergiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtraEnergiaRepository extends \Doctrine\ORM\EntityRepository
{
}
