<?php

namespace AppBundle\Repository;

/**
 * OtroRecursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtroRecursoRepository extends \Doctrine\ORM\EntityRepository
{
}
