<?php

namespace AppBundle\Repository;

/**
 * otro_recursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class otro_recursoRepository extends \Doctrine\ORM\EntityRepository
{
}
