<?php

namespace AppBundle\Repository;

/**
 * PartidaInmobiliariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartidaInmobiliariaRepository extends \Doctrine\ORM\EntityRepository
{
}
