<?php

namespace AppBundle\Repository;

/**
 * PeritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeritoRepository extends \Doctrine\ORM\EntityRepository
{
}
