<?php

namespace AppBundle\Repository;

/**
 * PlanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanoRepository extends \Doctrine\ORM\EntityRepository
{
}
