<?php

namespace AppBundle\Repository;

/**
 * ProcesoGranoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoGranoRepository extends \Doctrine\ORM\EntityRepository
{
}
