<?php

namespace AppBundle\Repository;

/**
 * ProductoServicioAuxiliarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoServicioAuxiliarRepository extends \Doctrine\ORM\EntityRepository
{
}
