<?php

namespace AppBundle\Repository;

/**
 * ResumenEjecutivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResumenEjecutivoRepository extends \Doctrine\ORM\EntityRepository
{
}
