<?php

namespace AppBundle\Repository;

/**
 * RiesgoPresuntoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiesgoPresuntoRepository extends \Doctrine\ORM\EntityRepository
{
}
