<?php

namespace AppBundle\Repository;

/**
 * RuidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuidoRepository extends \Doctrine\ORM\EntityRepository
{
}
