<?php

namespace AppBundle\Repository;

/**
 * ServidumbreAmbientalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServidumbreAmbientalRepository extends \Doctrine\ORM\EntityRepository
{
}
