<?php

namespace AppBundle\Repository;

/**
 * SitioContaminadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitioContaminadoRepository extends \Doctrine\ORM\EntityRepository
{
}
