<?php

namespace AppBundle\Repository;

/**
 * SubProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubProductoRepository extends \Doctrine\ORM\EntityRepository
{
}
