<?php

namespace AppBundle\Repository;

/**
 * SubTipoResiduoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubTipoResiduoRepository extends \Doctrine\ORM\EntityRepository
{
}
