<?php

namespace AppBundle\Repository;

/**
 * sueloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sueloRepository extends \Doctrine\ORM\EntityRepository
{
}
