<?php

namespace AppBundle\Repository;

/**
 * SustanciaRiesgosaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SustanciaRiesgosaRepository extends \Doctrine\ORM\EntityRepository
{
}
