<?php

namespace AppBundle\Repository;

/**
 * SustanciaTanqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SustanciaTanqueRepository extends \Doctrine\ORM\EntityRepository
{
}
