<?php

namespace AppBundle\Repository;

/**
 * SustanciaAuxiliarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SustanciaAuxiliarRepository extends \Doctrine\ORM\EntityRepository
{
}
