<?php

namespace AppBundle\Repository;

/**
 * TipoGasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoGasRepository extends \Doctrine\ORM\EntityRepository
{
}
