<?php

namespace AppBundle\Repository;

/**
 * TipoAplicacionAuxiliarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAplicacionAuxiliarRepository extends \Doctrine\ORM\EntityRepository
{
}
