<?php

namespace AppBundle\Repository;

/**
 * TipoAguaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAguaRepository extends \Doctrine\ORM\EntityRepository
{
}
