<?php

namespace AppBundle\Repository;

/**
 * TipoEfluenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEfluenteRepository extends \Doctrine\ORM\EntityRepository
{
}
