<?php

namespace AppBundle\Repository;

/**
 * TipoImpactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoImpactoRepository extends \Doctrine\ORM\EntityRepository
{
}
