<?php

namespace AppBundle\Repository;

/**
 * TipoBarreraArtificialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoBarreraArtificialRepository extends \Doctrine\ORM\EntityRepository
{
}
