<?php

namespace AppBundle\Repository;

/**
 * TipoAlmacenamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAlmacenamientoRepository extends \Doctrine\ORM\EntityRepository
{
}
