<?php

namespace AppBundle\Repository;

/**
 * TipoRuidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRuidoRepository extends \Doctrine\ORM\EntityRepository
{
}
