<?php

namespace AppBundle\Repository;

/**
 * TipoEmisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEmisionRepository extends \Doctrine\ORM\EntityRepository
{
}
