<?php

namespace AppBundle\Repository;

/**
 * TipoZonificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoZonificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
