<?php

namespace AppBundle\Repository;

/**
 * TipoResiduoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoResiduoRepository extends \Doctrine\ORM\EntityRepository
{
}
