<?php

namespace AppBundle\Repository;

/**
 * tipo_aguaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipo_aguaRepository extends \Doctrine\ORM\EntityRepository
{
}
