<?php

namespace AppBundle\Repository;

/**
 * TipoMonitoreoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoMonitoreoRepository extends \Doctrine\ORM\EntityRepository
{
}
