<?php

namespace AppBundle\Repository;

/**
 * TopografiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopografiaRepository extends \Doctrine\ORM\EntityRepository
{
}
