<?php

namespace AppBundle\Repository;

/**
 * TramitePlantaExpendioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramitePlantaExpendioRepository extends \Doctrine\ORM\EntityRepository
{
}
