<?php

namespace AppBundle\Repository;

/**
 * TratamientoPlantaPropiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TratamientoPlantaPropiaRepository extends \Doctrine\ORM\EntityRepository
{
}
