<?php

namespace AppBundle\Repository;

/**
 * TratamientoPlantaExteriorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TratamientoPlantaExteriorRepository extends \Doctrine\ORM\EntityRepository
{
}
