<?php

namespace AppBundle\Repository;

/**
 * UbicacionFeedlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UbicacionFeedlotRepository extends \Doctrine\ORM\EntityRepository
{
}
