<?php

namespace AppBundle\Repository;

/**
 * UrbanizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrbanizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
