<?php

namespace AppBundle\Repository;

/**
 * UsoRecursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsoRecursoRepository extends \Doctrine\ORM\EntityRepository
{
}
