<?php

namespace AppBundle\Repository;

/**
 * VientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VientoRepository extends \Doctrine\ORM\EntityRepository
{
}
