app:
    resource: '@AppBundle/Controller/'
    type: annotation

stg_theme:
    resource: '@STGThemeBundle/Controller/DefaultController.php'
    type:     annotation
    prefix:   /stgtheme

admin_login_cas:
    path: /admin/loginCAS
    defaults:
admin_logout_cas:
    path: /admin/logoutCAS
    defaults:
admin_failure_cas:
    path: /admin/failureCAS
    defaults: { _controller: AppBundle:Cas:failure }    
login_cas:
    path: /loginCAS
    defaults:
logout_cas:
    path: /logoutCAS
    defaults:
failure_cas:
    path: /failureCAS
    defaults: { _controller: AppBundle:Cas:failure }     

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

    
